### ISSUE TITLE
Is it possible to authenticate against Azure AD without using oidc-login

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [int128/kauthproxy#65]
I am using a managed AKS cluster and I am using the azure auth provider in my kube config. Is it possible to only use this plugin to authenticate against the provider. For example, my config looks like 

```
users:
  user:
    auth-provider:
      config:
        access-token: redacted
        apiserver-id: redacted
        client-id: redacted
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1589901220"
        refresh-token: redacted
        tenant-id: redacted
      name: azure
```
I want to use this configuration itself without adding another user item to work with `oidc-plugin`. I have already attempted a `kubectl auth-proxy -n kubernetes-dashboard https://kubernetes-dashboard.svc` using this user in the `context` but it gave me a error
```
error: could not run an authentication proxy: could not create a resolver: could not create a client: no Auth Provider found for name "azure"
exit status 1
```
This error seems to be coming from `client-credential` which is already a dependency of this project and the `client-credential` project has the azure login so I am not sure what I am missing here.

Any help is much appreciated.
